
spring:
  kafka:
    bootstrap-servers: 127.0.0.1:9092 #ָ��kafka server�ĵ�ַ����Ⱥ�������м䣬���Ÿ���
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: default_consumer_group #Ⱥ��ID
      enable-auto-commit: true
      auto-commit-interval: 1000
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
server:
  port: 8500
